/**
 * NeuroDOM Compiler — Main Entry
 * .nrd content → JavaScript agent definition object
 */

import { parseNRD } from "./parse.js";
import { compileFlows, compileGraph, compileState } from "./flow.js";

/**
 * Compile a .nrd string into a runtime agent definition.
 *
 * @param {string} content   Raw .nrd file content
 * @returns {AgentDefinition}
 */
export function compileNRD(content) {
  const ast = parseNRD(content);

  const def = {
    name: ast.name,

    identity: ast.identity,

    inputs: Object.fromEntries(ast.ports.in.map((p) => [p.name, p.type])),
    outputs: Object.fromEntries(ast.ports.out.map((p) => [p.name, p.type])),

    template: ast.template || null,

    state: compileState(ast.stateCode),

    flows: compileFlows(ast.flows),

    graph: compileGraph(ast.graphCode),

    soul: ast.soul || null,

    components: ast.components || [],
  };

  return def;
}

/**
 * Generate a JS module string from a compiled definition.
 * Useful for AOT build pipeline.
 */
export function generateModule(def) {
  // Serialize flows as code is complex — use runtime interpretation instead
  return `
// Auto-generated by NeuroDOM compiler
// Agent: ${def.name}
import { compileNRD } from "neurodom/compiler";

const __raw = ${JSON.stringify(_serializeDef(def))};

export default __raw;
`.trim();
}

function _serializeDef(def) {
  // Functions are not serializable; this is for metadata only
  return {
    name: def.name,
    identity: def.identity,
    inputs: def.inputs,
    outputs: def.outputs,
    template: def.template,
    graph: def.graph,
  };
}

export { parseNRD } from "./parse.js";
export { compileFlows, compileGraph, compileState } from "./flow.js";
